### ISSUE TITLE
Primer codereview

### ISSUE THREAD

**Issue by MarciaMillanao** [malditoprotozoo/picBeautifier-3000#4]
**Readme:** Falta detallar y explicar sobre la librería como por ejemplo: que es, como se utiliza, para que sirve, etc., no es necesario incluir la metodología de trabajo, ni describir el reto planteado .En la sección de requerimientos técnicos quedaría mejor 

> Para ésta librería utilizaremos las siguientes tecnologías:

y detallar las dependencias de desarrollo y producción utilizadas (npm es una dependencia de desarrollo), no olviden agregar las nuevas dependencias de testeo. Pueden utilizar como referencia los siguientes repositorios: https://github.com/needim/noty/blob/master/README.markdown https://github.com/GetmeUK/ContentTools/blob/master/README.md

**Issues:** Estan bien.

Lo demás esta ok, sigan trabajando así.

--
_Alexandra, Fabián y Marcia_

**Comment by toridoriv** [comment]
Corregido! Gracias por el feedback.

![bitmoji](https://render.bitstrips.com/v2/cpanel/645d7eb0-1570-4a35-9b45-a8783cfe681a-9f546997-2f5f-460e-99eb-21515e582fdf-v1.png?transparent=1&palette=1&width=246)
